# Generated by Django 5.2.2 on 2025-10-11 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi_laporan', models.TextField()),
                ('tanggal_laporan', models.DateTimeField(auto_now_add=True)),
                ('warga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='warga.warga')),
            ],
        ),
    ]
