# Generated by Django 5.2.2 on 2025-10-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0003_pengaduan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laporan',
        ),
    ]
